# my-prometheus/prometheus.yml
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - "observability/alerts/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fintech-app'
    static_configs:
      # We can add all our services here to be scraped.
      # The hostname (e.g., 'auth-service') is available inside the Docker network.
      - targets:
        - 'auth-service:80'
        - 'transactions-service:80'
        - 'tax-engine:80'
        # Add other services that expose a /metrics endpoint
